/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedCitizenRouteImport } from './routes/_authenticated/citizen'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDepartmentRouteImport } from './routes/_authenticated/department'
import { Route as AuthenticatedMyReportsRouteImport } from './routes/_authenticated/my-reports'
import { Route as AuthenticatedNearbyRouteImport } from './routes/_authenticated/nearby'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOfficerRouteImport } from './routes/_authenticated/officer'
import { Route as AuthenticatedOfficersRouteImport } from './routes/_authenticated/officers'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedComplaintsIdRouteImport } from './routes/_authenticated/complaints.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCitizenRoute = AuthenticatedCitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentRoute = AuthenticatedDepartmentRouteImport.update({
  id: '/department',
  path: '/department',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyReportsRoute = AuthenticatedMyReportsRouteImport.update({
  id: '/my-reports',
  path: '/my-reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNearbyRoute = AuthenticatedNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfficerRoute = AuthenticatedOfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfficersRoute = AuthenticatedOfficersRouteImport.update({
  id: '/officers',
  path: '/officers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplaintsIdRoute =
  AuthenticatedComplaintsIdRouteImport.update({
    id: '/complaints/$id',
    path: '/complaints/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/citizen': typeof AuthenticatedCitizenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/department': typeof AuthenticatedDepartmentRoute
  '/my-reports': typeof AuthenticatedMyReportsRoute
  '/nearby': typeof AuthenticatedNearbyRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/officer': typeof AuthenticatedOfficerRoute
  '/officers': typeof AuthenticatedOfficersRoute
  '/report': typeof AuthenticatedReportRoute
  '/complaints/$id': typeof AuthenticatedComplaintsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/citizen': typeof AuthenticatedCitizenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/department': typeof AuthenticatedDepartmentRoute
  '/my-reports': typeof AuthenticatedMyReportsRoute
  '/nearby': typeof AuthenticatedNearbyRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/officer': typeof AuthenticatedOfficerRoute
  '/officers': typeof AuthenticatedOfficersRoute
  '/report': typeof AuthenticatedReportRoute
  '/complaints/$id': typeof AuthenticatedComplaintsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/citizen': typeof AuthenticatedCitizenRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/department': typeof AuthenticatedDepartmentRoute
  '/_authenticated/my-reports': typeof AuthenticatedMyReportsRoute
  '/_authenticated/nearby': typeof AuthenticatedNearbyRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/officer': typeof AuthenticatedOfficerRoute
  '/_authenticated/officers': typeof AuthenticatedOfficersRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/complaints/$id': typeof AuthenticatedComplaintsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/citizen'
    | '/dashboard'
    | '/department'
    | '/my-reports'
    | '/nearby'
    | '/notifications'
    | '/officer'
    | '/officers'
    | '/report'
    | '/complaints/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/citizen'
    | '/dashboard'
    | '/department'
    | '/my-reports'
    | '/nearby'
    | '/notifications'
    | '/officer'
    | '/officers'
    | '/report'
    | '/complaints/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/citizen'
    | '/_authenticated/dashboard'
    | '/_authenticated/department'
    | '/_authenticated/my-reports'
    | '/_authenticated/nearby'
    | '/_authenticated/notifications'
    | '/_authenticated/officer'
    | '/_authenticated/officers'
    | '/_authenticated/report'
    | '/_authenticated/complaints/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizen': {
      id: '/_authenticated/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof AuthenticatedCitizenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/department': {
      id: '/_authenticated/department'
      path: '/department'
      fullPath: '/department'
      preLoaderRoute: typeof AuthenticatedDepartmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-reports': {
      id: '/_authenticated/my-reports'
      path: '/my-reports'
      fullPath: '/my-reports'
      preLoaderRoute: typeof AuthenticatedMyReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nearby': {
      id: '/_authenticated/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof AuthenticatedNearbyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/officer': {
      id: '/_authenticated/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof AuthenticatedOfficerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/officers': {
      id: '/_authenticated/officers'
      path: '/officers'
      fullPath: '/officers'
      preLoaderRoute: typeof AuthenticatedOfficersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complaints/$id': {
      id: '/_authenticated/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof AuthenticatedComplaintsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCitizenRoute: typeof AuthenticatedCitizenRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentRoute: typeof AuthenticatedDepartmentRoute
  AuthenticatedMyReportsRoute: typeof AuthenticatedMyReportsRoute
  AuthenticatedNearbyRoute: typeof AuthenticatedNearbyRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOfficerRoute: typeof AuthenticatedOfficerRoute
  AuthenticatedOfficersRoute: typeof AuthenticatedOfficersRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedComplaintsIdRoute: typeof AuthenticatedComplaintsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCitizenRoute: AuthenticatedCitizenRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentRoute: AuthenticatedDepartmentRoute,
  AuthenticatedMyReportsRoute: AuthenticatedMyReportsRoute,
  AuthenticatedNearbyRoute: AuthenticatedNearbyRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOfficerRoute: AuthenticatedOfficerRoute,
  AuthenticatedOfficersRoute: AuthenticatedOfficersRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedComplaintsIdRoute: AuthenticatedComplaintsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
